#!/bin/sh
### BEGIN INIT INFO
# Provides: noded
# Required-Start:	$syslog $local_fs $remote_fs $network
# Required-Stop:	$syslog $local_fs $remote_fs $network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: <%= appName %> nodejs daemon
### END INIT INFO
. /etc/init.d/functions
. /lib/lsb/init-functions
export ROOT_URL=<%= appRootUrl %>
export PORT=<%= appPort %>
export NODE_ENV=production
export MONGO_URL=<%= appMongoUrl %>
export METEOR_SETTINGS=<%- appEnv %>
prog=<%= appName %>
PIDFILE=/var/run/$prog.pid
DESC="<%= appName %> nodejs daemon"
start() {
	start_daemon -p $PIDFILE /usr/bin/node /var/www/<%= appName %>/bundle/main.js &
	if [ $? -ne 0 ]
	then
		exit 1
	fi
	exit 0
}

stop() {
	killproc -p $PIDFILE
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}

force_reload() {
	stop
	start

}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	force-reload)
		force_reload
		;;
	restart)
		stop
		start
		;;

	*)
		echo "$Usage: $prog {start|stop|force-reload|restart}"
		exit 2
esac
